=== AndresReyesE/7.-Sexto-semestre/Manejadores de bases de datos/FAMILY/family.xsd
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by JosÃ© Luis Zechinelli Martini (UDLA) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="age" type="xs:decimal"/>
				<xs:element name="email" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
			<xs:attribute name="mother" type="xs:IDREF"/>
			<xs:attribute name="father" type="xs:IDREF"/>
			<xs:attribute name="children" type="xs:IDREFS"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="family">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="person" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AndresReyesE/7.-Sexto-semestre/Manejadores de bases de datos/FAMILY/family.xml
<!DOCTYPE family SYSTEM "family.dtd">
<!--<family xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="family.xsd">-->
<family>
	<person id="john" children="jane jack">
		<name> John Smith </name><age>38</age><email></email>
	</person>
	<person id="mary" children="jane jack">
		<name> Mary Smith </name><age>38</age><email></email>
	</person>
	<person id="jane" mother="mary" father="john">
		<name> Jane Smith </name><age>18</age><email></email>
	</person>
	<person id="jack" mother="mary" father="john">
		<name> Jack Smith </name><age>16</age><email></email>
	</person>
</family>
